package com.commonsware.todo.ui.roster

import android.graphics.Paint //added for strikethrough
import androidx.recyclerview.widget.RecyclerView
import com.commonsware.todo.databinding.TodoRowBinding
import com.commonsware.todo.repo.ToDoModel

/**
 * A ViewHolder that describes a single to-do item's view and metadata within the RecyclerView.
 * Its primary job is to hold onto the view for a single row (defined in todo_row.xml)
 * and bind a specific ToDoModel to that view.
 *
 * @param binding An instance of TodoRowBinding, generated by the ViewBinding library.
 *                It provides direct and type-safe access to all the views within the todo_row.xml layout.
 * @param onCheckBoxToggle A lambda function that will be invoked when the user taps the checkbox.
 *                         It passes the specific ToDoModel of the row that was toggled.
 * @param onRowClick A lambda function that will be invoked when the user clicks anywhere on the row.
 *                   It passes the ToDoModel for that row, allowing for navigation to a detail screen.
 */
class RosterRowHolder(
    private val binding: TodoRowBinding,
    val onCheckBoxToggle: (ToDoModel) -> Unit,
    val onRowClick: (ToDoModel) -> Unit
) : RecyclerView.ViewHolder(binding.root) {

    /**
     * Binds a ToDoModel object to the views held by this ViewHolder.
     * This function is called by the RecyclerView.Adapter for each row to display its data.
     *
     * @param model The data model for the current row.
     */
    fun bind(model: ToDoModel) {
        // 'binding.apply' allows us to access views from todo_row.xml directly.
        binding.apply {
            // Set a click listener on the entire row view. When clicked, invoke the onRowClick lambda.
            root.setOnClickListener { onRowClick(model) }

            // Set the checkbox's state based on the model's 'isCompleted' property.
            isCompletedCB.isChecked = model.isCompleted

            // Set a listener to react to changes in the checkbox's state.
            // When toggled, invoke the onCheckBoxToggle lambda.
            isCompletedCB.setOnCheckedChangeListener { _, _ -> onCheckBoxToggle(model) }

            // Set the TextView to display the item's description.
            desc.text = model.description

            // --- NEW FEATURE ADDED HERE ---
            // Add or remove the strikethrough flag based on the item's completion status.
            if (model.isCompleted) {
                desc.paintFlags = desc.paintFlags or Paint.STRIKE_THRU_TEXT_FLAG
            } else {
                desc.paintFlags = desc.paintFlags and Paint.STRIKE_THRU_TEXT_FLAG.inv()
            }
        }
    }
}
